### ISSUE TITLE
Consumer configured via application.yml not working

### ISSUE THREAD

**Issue by gtors** [budjb/grails-rabbitmq-native#136]
With configuration below, the consumer class is not listen incoming messages and not displayed in active connections of RabbitMQ

application.yml:
```yml
rabbitmq:
    connections:
      - name: default
        host: localhost
        username: guest
        password: guest
    queues:
      - name:  test
        durable: true
    consumers:
      MyConsumer:
        queue: test
```

MyConsumer.groovy:
```groovy
class MyConsumer {

    // static rabbitConfig = [
    //    "queue": "test"
    // ]

    def handleMessage(String body, MessageContext context) {
       // ...
    }
}
```
But, if uncomment  `rabbitConfig` in the class and remove configuration of consumer from `application.yml`, then all works as expected.

**Comment by gtors** [comment]
Fixed this by changing config: 

```yml
    consumers:
      MyConsumer:
        queue: test
        match: all
```

**Comment by kuceram** [comment]
Why closing this? I think that the `match` attribute should not be required. If it is required, than I would mention it in docs.

**Comment by budjb** [comment]
I'd need more information to be able to understand what's going on here, but `match` is only required when using a `header` exchange. I don't see an exchange configuration here (or binding, for that matter). @gtors what kind of exchange is that queue bound to, or is it? And how are you sending messages to that queue?

**Comment by gtors** [comment]
I no longer have access to the source code. But as far as I remember, the default exchange was used (i.e. it wasn't explicitly configured)

**Comment by kuceram** [comment]
In our case, we have following configuration:
Grails: 3.3.9
rabbitmq-native: 3.4.5

```yaml
rabbitmq:
    connections:
        - host: my.host.com
          username: rabbitmg
          password: rabbitmg
          virtualHost: rabbitmg
          isDefault: true
          requestedHeartbeat: 10
    exchanges:
        - name: amq.topic
          type: topic
          durable: true
    queues:
        - name: my-server:message
          durable: true
          exchange: amq.topic
          binding: 'message.#'
    consumers:
        MessageConsumer:
            queue: my-server:message
```
This doesn't work: I don't receive the message into MessageConsumer:
```groovy
class MessageConsumer {

    def handleMessage(def body) {
        log.debug("received rabbitmq message $body")
    }
}
```

When we add `match: all` to the configuration, it starts magically work:
```yaml
rabbitmq:
    ...
    consumers:
        MessageConsumer:
            queue: my-server:message
            match: all
```
