### ISSUE TITLE
Unable to define consumer autoAck in yaml

### ISSUE THREAD

**Issue by kuceram** [budjb/grails-rabbitmq-native#140]
It is not possible to define `consumer.autoAck` in `application.yml` as it requires enum and yaml can serve only string and numbers.

I would suggest to provide enum full name in config:
```yaml
rabbitmq:
    ...
    consumers:
        MyConsumer:
            autoAck: com.budjb.rabbitmq.consumer.AutoAck.MANUAL
```

Then you can parse it here: https://github.com/budjb/grails-rabbitmq-native/blob/grails-3.x/rabbitmq-native/src/main/groovy/com/budjb/rabbitmq/consumer/LegacyConsumerContext.groovy#L276
